// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasks.Data.Context;

namespace Tasks.Data.Migrations
{
    [DbContext(typeof(TasksContext))]
    partial class TasksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tasks.Domain.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Apelido")
                        .HasMaxLength(80);

                    b.Property<DateTime?>("DataDeAlteracao");

                    b.Property<DateTime>("DataDeCadastro");

                    b.Property<DateTime?>("DataDeExclusao");

                    b.Property<string>("Email")
                        .HasMaxLength(120);

                    b.Property<bool>("Excluido");

                    b.Property<string>("Senha")
                        .HasMaxLength(35);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tasks.Domain.Entidades.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime?>("Conclusao");

                    b.Property<DateTime?>("DataDeAlteracao");

                    b.Property<DateTime>("DataDeCadastro");

                    b.Property<DateTime?>("DataDeExclusao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500);

                    b.Property<bool>("Excluido");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150);

                    b.Property<Guid>("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
